export const initialEquipment = [
  {
    name: 'Sony FX3',
    category: 'cameras',
    role: 'Full-Frame Cinema Camera',
    badge: '4K 120p',
    icon: 'Video',
    keyFeatures: [
      'Full-Frame 12.1MP Sensor',
      '15+ Stops Dynamic Range',
      'Dual Base ISO (800 / 12,800)',
      'S-Cinetone Film Color Science',
    ],
    specs: [
      { label: 'Sensor', value: '35mm Full-Frame Exmor R CMOS' },
      { label: 'Recording', value: '4K 120p / FHD 240p 10-bit 4:2:2' },
      { label: 'ISO Range', value: '80–102,400 (Exp: 80–409,600)' },
      { label: 'Stabilization', value: '5-Axis In-Body Active IS' },
    ],
    featuredIn: ['Sarah & Youssef', 'The Sunset Vows', 'Leila & Amine'],
    order: 1,
    active: true,
  },
  {
    name: 'Sony α7R V',
    category: 'cameras',
    role: 'Full-Frame Master Stills & Hybrid',
    badge: '61MP RAW',
    icon: 'Camera',
    keyFeatures: [
      '61.0MP Back-Illuminated CMOS',
      'AI-Powered Real-Time AF Tracking',
      '16-bit Uncompressed RAW Stills',
      'Dual CFexpress Type A / SD Slots',
    ],
    specs: [
      { label: 'Sensor', value: '35.7 × 23.8mm Exmor R CMOS' },
      { label: 'Resolution', value: '9504 × 6336 px Master Files' },
      { label: 'ISO Range', value: '100–32,000 (Exp: 50–102,400)' },
      { label: 'Stabilization', value: '8-Stop 5-Axis In-Body' },
    ],
    featuredIn: ['Elena — Carthage', 'Heirloom Florals', 'La Marsa Palace'],
    order: 2,
    active: true,
  },
  {
    name: 'Sony G-Master Primes',
    category: 'lenses',
    role: '24mm f/1.4 · 50mm f/1.2 · 85mm f/1.4',
    badge: 'f/1.2 Master Glass',
    icon: 'Sparkles',
    keyFeatures: [
      'XA Extreme Aspherical Elements',
      'Creamy Cinematic Bokeh Falloff',
      'Nano AR Coating II Glare Reduction',
      'Dual XD Linear Motors for Silent AF',
    ],
    specs: [
      { label: 'Aperture Range', value: 'f/1.2 – f/16 Constant Sharpness' },
      { label: 'Optics System', value: '14 Elements in 10 Groups' },
      { label: 'Filter Diameter', value: '67mm / 72mm / 77mm' },
      { label: 'Coating', value: 'Fluorine & Nano AR II' },
    ],
    featuredIn: ['The Sunset Vows', 'Sarah & Youssef', 'Editorial Portraits'],
    order: 3,
    active: true,
  },
  {
    name: 'DJI Mavic 3 Cine',
    category: 'aerial',
    role: 'Dual-Camera Cinema Aerial Drone',
    badge: '5.1K ProRes',
    icon: 'Compass',
    keyFeatures: [
      '4/3 CMOS Hasselblad Camera',
      'Apple ProRes 422 HQ Direct Capture',
      'Omnidirectional Obstacle Sensing',
      '46-Minute Extended Flight Time',
    ],
    specs: [
      { label: 'Sensor', value: '4/3 CMOS 20MP Hasselblad' },
      { label: 'Max Video', value: '5.1K at 50fps / 4K at 120fps' },
      { label: 'Internal Storage', value: '1TB High-Speed SSD' },
      { label: 'Transmission', value: 'O3+ 15km 1080p 60fps' },
    ],
    featuredIn: ['Mediterranean Coast', 'Carthage Ruins', 'Sidi Bou Said'],
    order: 4,
    active: true,
  },
];

export const initialServices = [
  {
    title: 'PACK ESSENTIEL',
    subtitle: 'Réception 2H',
    badge: '',
    price: 'Tarifs sur demande',
    description: 'Photos numériques illimitées, vidéo teaser 4K ou reels cinématiques, livraison sur flash.',
    icon: 'Camera',
    features: [
      'Photos numériques illimitées',
      'Vidéo teaser 4K ou 2 Reels cinématiques',
      'Livraison sur flash',
    ],
    options: [
      'Préparatifs',
      'Reel cinématique',
      'Shooting extérieur',
      'Drone aérien 4K',
      'Tableau MDF 30×40',
      'Album photo & Tirages',
      'Grue 7M Pro',
    ],
    order: 1,
    active: true,
  },
  {
    title: 'PACK BASIC',
    subtitle: 'Cérémonie & Soirée',
    badge: '',
    price: 'Tarifs sur demande',
    description: 'Reportage vidéo 4K, aftermovie cinématique, photos illimitées et 50 tirages imprimés.',
    icon: 'Video',
    features: [
      'Reportage vidéo 4K',
      'Aftermovie cinématique',
      'Photos numériques illimitées',
      '50 photos imprimées',
      'Livraison sur flash',
    ],
    options: [
      'Préparatifs',
      'Reel cinématique supplémentaire',
      'Shooting extérieur',
      'Drone aérien 4K',
      'Tableau MDF 30×40',
      'Album photo / PhotoBook Luxe',
      'Grue 7M Pro',
      'Livraison prioritaire',
    ],
    order: 2,
    active: true,
  },
  {
    title: 'PACK STANDARD',
    subtitle: 'Le choix coup de cœur',
    badge: 'MEILLEURE OFFRE',
    price: 'Tarifs sur demande',
    description: 'Formule complète avec reportage 4K, drone, shooting extérieur, 1 reel, tableau MDF et album photo offert.',
    icon: 'Gem',
    features: [
      'Reportage vidéo 4K',
      'Aftermovie cinématique',
      'Photos numériques illimitées',
      '80 photos imprimées',
      'Shooting extérieur',
      'Drone',
      '1 Reel cinématique',
      'Tableau MDF 30×40 offert',
      'Album photo offert',
      'Préparatifs inclus',
    ],
    options: [
      'Grue 7M Pro',
      '2ème Reel cinématique',
      'PhotoBook Luxe 15 pages',
      'Livraison prioritaire',
      'Séance After-Day / Engagement',
    ],
    order: 3,
    active: true,
  },
  {
    title: 'PACK PREMIUM SIGNATURE',
    subtitle: "L'expérience haute couture",
    badge: 'SIGNATURE',
    price: 'Tarifs sur demande',
    description: 'Production prestige avec grue 7M pro, drone, 100 tirages, PhotoBook Luxe 15 pages et livraison prioritaire.',
    icon: 'Crown',
    features: [
      'Reportage vidéo 4K',
      'Aftermovie cinématique',
      'Photos numériques illimitées',
      '100 photos imprimées',
      'Shooting extérieur',
      'Drone',
      'Grue 7M Pro',
      '2 Reels cinématiques',
      'PhotoBook Luxe 15 pages',
      'Tableau MDF 30×40 offert',
      'Album photo offert',
      'Préparatifs inclus',
      'Livraison prioritaire',
    ],
    options: [],
    order: 4,
    active: true,
  },
];

export const initialWorkCategories = [
  {
    name: 'Photography',
    slug: 'photography',
    description: 'Fine art still captures, portraits, and heirloom details.',
    order: 1,
    active: true,
  },
  {
    name: 'Films',
    slug: 'films',
    description: 'Cinematic wedding films and documentary reels.',
    order: 2,
    active: true,
  },
  {
    name: 'Super 8mm',
    slug: 'super-8mm',
    description: 'Nostalgic analog motion picture reels.',
    order: 3,
    active: true,
  },
  {
    name: 'Editorial & Destination',
    slug: 'editorial-destination',
    description: 'Curated editorial fashion and international destination celebrations.',
    order: 4,
    active: true,
  },
];

export const initialPortfolioPosts = [
  {
    _id: 'post-rades-vows',
    title: 'The Radès Shoreline',
    slug: 'rades-shoreline',
    location: 'Radès, Tunisia · 2024',
    year: '2024',
    category: 'photography',
    coverImage: '/portfolio/images/rades-vows-landscape.jpg',
    videoUrl: '',
    media: [
      { url: '/portfolio/images/rades-vows-landscape.jpg', type: 'photo', caption: 'Shoreline exchange of vows at sunset', aspectRatio: '16/10' },
      { url: '/portfolio/images/rades-portrait.jpg', type: 'photo', caption: 'Editorial portrait against Mediterranean backdrop', aspectRatio: '4/5' },
      { url: '/portfolio/images/bridal-veil.jpg', type: 'photo', caption: 'Handcrafted lace veil in natural daylight', aspectRatio: '4/5' },
      { url: '/portfolio/images/heirloom-portrait.jpg', type: 'photo', caption: 'Heirloom bridal florals and palace architecture', aspectRatio: '4/5' },
    ],
    featured: true,
    order: 1,
  },
  {
    _id: 'post-sunset-vows-film',
    title: 'The Sunset Reel',
    slug: 'sunset-vows-film',
    location: 'Sidi Bou Said · 4K Film',
    year: '2024',
    category: 'film',
    coverImage: '/portfolio/images/rades-portrait.jpg',
    videoUrl: '/portfolio/videos/reel-1.mp4',
    media: [
      { url: '/portfolio/videos/reel-1.mp4', type: 'video', caption: 'Cinematic teaser reel filmed in Sidi Bou Said', aspectRatio: '9/16' },
      { url: '/portfolio/images/rades-portrait.jpg', type: 'photo', caption: 'Film still — golden hour portrait', aspectRatio: '4/5' },
      { url: '/portfolio/images/rades-vows-landscape.jpg', type: 'photo', caption: 'Film still — vows by the sea', aspectRatio: '16/10' },
    ],
    featured: true,
    order: 2,
  },
  {
    _id: 'post-ayoub-dorsaf',
    title: 'Ayoub & Dorsaf',
    slug: 'ayoub-dorsaf',
    location: 'Gammarth Hills · 2024',
    year: '2024',
    category: 'photography',
    coverImage: '/portfolio/images/ayoub-dorsaf-golden.jpg',
    videoUrl: '',
    media: [
      { url: '/portfolio/images/ayoub-dorsaf-golden.jpg', type: 'photo', caption: 'Sunset couple portrait overlooking the bay', aspectRatio: '16/10' },
      { url: '/portfolio/images/ayoub-dorsaf-sunset.jpg', type: 'photo', caption: 'Intimate candid moment during golden hour', aspectRatio: '16/10' },
      { url: '/portfolio/images/ayoub-dorsaf-celebration.jpg', type: 'photo', caption: 'Celebration and laughter with family', aspectRatio: '16/10' },
      { url: '/portfolio/images/carthage-elegance.jpg', type: 'photo', caption: 'Timeless portrait in black & white', aspectRatio: '1/1' },
    ],
    featured: true,
    order: 3,
  },
  {
    _id: 'post-golden-hour-film',
    title: 'Mediterranean Golden Hour',
    slug: 'mediterranean-golden-hour',
    location: 'Mediterranean Coast · 4K Film',
    year: '2024',
    category: 'film',
    coverImage: '/portfolio/images/ayoub-dorsaf-sunset.jpg',
    videoUrl: '/portfolio/videos/reel-2.mp4',
    media: [
      { url: '/portfolio/videos/reel-2.mp4', type: 'video', caption: 'Cinematic 4K wedding highlight reel', aspectRatio: '9/16' },
      { url: '/portfolio/images/ayoub-dorsaf-sunset.jpg', type: 'photo', caption: 'Film still — golden hour glow', aspectRatio: '16/10' },
      { url: '/portfolio/images/ayoub-dorsaf-celebration.jpg', type: 'photo', caption: 'Film still — evening reception entrance', aspectRatio: '16/10' },
    ],
    featured: true,
    order: 4,
  },
  {
    _id: 'post-tunisian-heritage',
    title: 'Tunisian Heritage Edition',
    slug: 'tunisian-heritage-edition',
    location: 'Medina Palace · Traditional Wteya',
    year: '2024',
    category: 'photography',
    coverImage: '/portfolio/images/traditional-heritage.jpg',
    videoUrl: '',
    media: [
      { url: '/portfolio/images/traditional-heritage.jpg', type: 'photo', caption: 'Embroidered traditional bridal gown & jewelry', aspectRatio: '16/10' },
      { url: '/portfolio/images/hedi-zaibi-portrait.jpg', type: 'photo', caption: 'Classic palace courtyard portrait', aspectRatio: '4/5' },
      { url: '/portfolio/images/heirloom-portrait.jpg', type: 'photo', caption: 'Bridal details and traditional henna celebration', aspectRatio: '4/5' },
      { url: '/portfolio/images/carthage-elegance.jpg', type: 'photo', caption: 'Family heirloom elegance', aspectRatio: '1/1' },
    ],
    featured: true,
    order: 5,
  },
];
